server:
  port: 8001

dubbo:
  application:
    #注册地址
    name: demo-provider
  registry:
    address: zookeeper://127.0.0.1:2188
  protocol:
      name: dubbo
      prot: 20880
  provider:
      timeout: 10000
      retries: 0
      delay: -1